### ISSUE TITLE
IndexError when loading seed with different canvas size

### ISSUE THREAD

**Issue by sich97** [sich97/Conways-Game-of-Life#7]
The feature of loading seed from file, even with different canvas sizes, used to work fine during testing. But since then I've changed some stuff, so I might have to go over it again.

Error message:
Traceback (most recent call last):
  File "CGL.py", line 781, in <module>
    main()
  File "CGL.py", line 83, in main
    max_auto_seed_percent, canvas, drawn_cells, current_seed)
  File "CGL.py", line 373, in new_simulation
    apply_seed(grid, current_seed)
  File "CGL.py", line 475, in apply_seed
    grid[y][x] = 1
IndexError: list assignment index out of range

**Comment by sich97** [comment]
Allthough the program accounts for resizing the canvas appropriately when loading a seed with a smaller canvas size than default, it doesn't work when loading a seed with a greater canvas size than default.

**Comment by sich97** [comment]
Fixed in commit: 6baac6c6f7403bca3907e53e9c4d6f0f90be2831
